// Optional browser QA tool, not a runtime dependency. Set PLAYWRIGHT_MODULE if needed.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
require('node:fs').mkdirSync('work',{recursive:true});
const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:1440,height:1080}});const errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4173/?test=1');await page.waitForFunction(()=>!document.querySelector('#start').disabled);
await page.screenshot({path:'work/menu.png'});
await page.click('#mobile-play');await page.click('[data-difficulty="elite"]');await page.click('#mobile-duel');
await page.waitForFunction(()=>window.__jetclash.match.state==='PLAYING');
const x=await page.evaluate(()=>window.__jetclash.match.player.x);
await page.keyboard.down('ArrowRight');await page.waitForTimeout(400);await page.keyboard.up('ArrowRight');
assert.ok(await page.evaluate(x=>window.__jetclash.match.player.x>x,x));
await page.keyboard.down('Space');await page.waitForTimeout(100);await page.keyboard.up('Space');
assert.ok(await page.evaluate(()=>window.__jetclash.match.player.y<590));
await page.keyboard.down('ShiftLeft');await page.waitForTimeout(600);await page.keyboard.up('ShiftLeft');
const fuel=await page.evaluate(()=>window.__jetclash.match.player.fuel);assert.ok(fuel<95);
await page.waitForTimeout(300);assert.ok(await page.evaluate(v=>window.__jetclash.match.player.fuel>v,fuel));
await page.screenshot({path:'work/playing.png'});
await page.evaluate(()=>{const {match:m}=window.__jetclash;Object.assign(m.ball,{x:1220,y:448,vx:0,vy:0});});
await page.waitForFunction(()=>window.__jetclash.match.state==='GOAL_SCORED');assert.equal(await page.locator('#score-player').textContent(),'1');
await page.screenshot({path:'work/goal.png'});
await page.waitForFunction(()=>window.__jetclash.match.state==='PLAYING');
await page.evaluate(()=>{const m=window.__jetclash.match;Object.assign(m.ball,{x:60,y:448,vx:0,vy:0});});
await page.waitForFunction(()=>window.__jetclash.match.state==='GOAL_SCORED');
await page.waitForFunction(()=>window.__jetclash.match.state==='PLAYING');
await page.evaluate(()=>window.__jetclash.match.remaining=.02);
await page.waitForFunction(()=>window.__jetclash.match.overtime);assert.equal(await page.locator('#mode-label').textContent(),'MORT SUBITE');
await page.screenshot({path:'work/overtime.png'});
await page.evaluate(()=>Object.assign(window.__jetclash.match.ball,{x:1220,y:448,vx:0,vy:0}));
await page.waitForFunction(()=>window.__jetclash.match.state==='POST_MATCH');
assert.equal(await page.locator('#xp-earned').textContent(),'+170 XP');
await page.screenshot({path:'work/result.png'});
await page.click('#replay');await page.waitForFunction(()=>window.__jetclash.match.state==='PLAYING');
await page.evaluate(()=>{const m=window.__jetclash.match;m.score.bot=1;m.remaining=.01;});await page.waitForFunction(()=>window.__jetclash.match.state==='POST_MATCH');
await page.click('#back-menu');await page.locator('#mobile-menu').waitFor({state:'visible'});
await page.reload();await page.waitForFunction(()=>!document.querySelector('#start').disabled);await page.waitForFunction(()=>document.querySelector('[data-profile-level]').textContent.includes('270 / 1 000 XP'));assert.equal(await page.evaluate(()=>window.__jetclash.match.profile.data.xp),270);
await page.setViewportSize({width:1024,height:768});await page.screenshot({path:'work/menu-1024.png'});
assert.deepEqual(errors,[]);console.log('Browser checks OK: menu, difficulty, countdown, keyboard, jump, boost/recharge, goals, reset, overtime, XP, replay, menu, reload. No JS errors.');
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
