import test from 'node:test';
import assert from 'node:assert/strict';
import {ProfileStore} from '../src/profile-store.js';
import {Match,STATES} from '../src/match.js';
const KEY='jetclash.etape2.profile.v1';
function fixture(saved){const values=new Map(saved?[[KEY,JSON.stringify(saved)]]:[]);let now=Date.parse('2026-10-07T12:00:00Z');const storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)};const profile=new ProfileStore(storage,()=>now);return {profile,storage,setTime:t=>now=Date.parse(t),reload:()=>new ProfileStore(storage,()=>now)};}
const entry=(p,id)=>p.challenges.snapshot().items.find(d=>d.id===id);
test('progression simultanée, seuil exact, plafond et récompense unique',()=>{const {profile:p,reload}=fixture();p.challenges.record('goals');assert.equal(entry(p,'d-goals-2').progress,1);assert.equal(p.data.seasonXp,0);p.challenges.record('goals');assert.equal(entry(p,'d-goals-2').claimed,true);assert.equal(entry(p,'d-goals-3').claimed,false);assert.equal(p.data.seasonXp,100);p.challenges.record('goals',999);assert.equal(entry(p,'w-goals').progress,15);assert.equal(p.data.seasonXp,750);const q=reload();assert.equal(entry(q,'w-goals').claimed,true);q.challenges.record('goals',999);assert.equal(q.data.seasonXp,750);});
test('événements invalides ignorés et objectif non atteint non récompensé',()=>{const {profile:p}=fixture();for(const n of [-1,0,NaN,Infinity,1.5])p.challenges.record('goals',n);p.challenges.record('unknown',50);assert.equal(entry(p,'d-goals-2').progress,0);assert.equal(p.data.seasonXp,0);});
test('migration et resets conservent toutes les autres données',()=>{const original={xp:1160,completed:['old'],coins:88,skins:['fluid'],settings:{sound:false},progression:{rank:2}};const f=fixture(original),p=f.profile;p.challenges.record('goals');p.challenges.record('training');const xp=p.data.seasonXp;f.setTime('2026-10-08T00:00:00Z');assert.equal(entry(p,'d-goals-2').progress,0);assert.equal(entry(p,'d-training').claimed,false);assert.equal(entry(p,'w-goals').progress,1);assert.equal(p.data.seasonXp,xp);f.setTime('2026-10-12T00:00:00Z');assert.equal(entry(p,'w-goals').progress,0);const q=f.reload();for(const [key,value] of Object.entries(original))assert.deepEqual(q.data[key],value);assert.equal(q.data.seasonXp,xp);});
test('minuit UTC, lundi et retour de l’horloge',()=>{const f=fixture(),p=f.profile;f.setTime('2026-10-11T23:59:59Z');p.challenges.record('matches');assert.equal(p.data.challenges.weekly.key,'2026-10-05');f.setTime('2026-10-12T00:00:00Z');assert.equal(entry(p,'w-matches').progress,0);p.challenges.record('matches');const xp=p.data.seasonXp;f.setTime('2026-10-11T12:00:00Z');assert.equal(entry(p,'d-match-1').claimed,true);p.challenges.record('matches');assert.equal(p.data.seasonXp,xp);});
test('état partiellement invalide réparé sans toucher au profil',()=>{const {profile:p}=fixture({xp:12,completed:[],coins:9,seasonXp:-1,challenges:{daily:{key:'2026-10-07',entries:{'d-goals-2':{progress:999,claimed:true}}},weekly:[]}});assert.equal(p.data.xp,12);assert.equal(p.data.coins,9);assert.equal(entry(p,'d-goals-2').progress,2);p.challenges.record('goals');assert.equal(p.data.seasonXp,0);});
test('stockage indisponible : jeu et récompense unique dans la session',()=>{const p=new ProfileStore({getItem(){throw Error();},setItem(){throw Error();}});p.challenges.record('training');p.challenges.record('training');assert.equal(p.data.seasonXp,75);assert.ok(p.warning);});
test('intégration : abandon, bot, entraînement, buts et fin unique',()=>{const {profile:p}=fixture(),m=new Match(p);m.start();m.menu();assert.equal(entry(p,'d-match-1').progress,0);m.start('training');assert.equal(p.data.seasonXp,75);m.goal('player');assert.equal(entry(p,'d-goals-2').progress,0);m.start();m.state=STATES.PLAYING;m.goal('bot');assert.equal(entry(p,'d-goals-2').progress,0);m.state=STATES.PLAYING;m.goal('player');assert.equal(m.goal('player'),false);assert.equal(entry(p,'d-goals-2').progress,1);m.state=STATES.PLAYING;m.score.player=2;m.finish();assert.equal(entry(p,'d-match-1').claimed,true);assert.equal(entry(p,'d-win').claimed,true);const xp=p.data.seasonXp;assert.equal(m.finish(),false);assert.equal(p.data.seasonXp,xp);});
