import test from 'node:test';
import assert from 'node:assert/strict';
import {ProfileStore} from '../src/profile-store.js';
import {COSMETIC_SLOTS,cosmeticVisual} from '../src/collection.js';
function fixture(){let raw;const storage={getItem:()=>raw,setItem:(_k,v)=>raw=v};const p=new ProfileStore(storage);p.pass.addXp(50000);p.pass.setPremium(true);return {p,storage};}
test('crate opens once, preserves balances and reward across reload',()=>{const {p,storage}=fixture();p.pass.claim(3,'free');const before=[p.data.xp,p.data.coins,p.data.tokens,p.data.seasonXp];const reward=p.collection.open('s1-free-3',()=>.999);assert.ok(reward);assert.equal(p.collection.open('s1-free-3'),null);assert.equal(p.data.passInventory.length,2);assert.deepEqual([p.data.xp,p.data.coins,p.data.tokens,p.data.seasonXp],before);assert.ok(p.collection.equip(reward.id));const reload=new ProfileStore(storage);assert.deepEqual(reload.collection.equipped(reward.type),reward);assert.equal(reload.collection.open('s1-free-3'),null);assert.equal(reload.collection.unequip(reward.type),true);assert.equal(new ProfileStore(storage).collection.equipped(reward.type),undefined);});
test('crate pool covers every slot and palette, rejects invalid random and unknown objects',()=>{for(let i=0;i<20;i++){const {p}=fixture();p.pass.claim(3,'free');const item=p.collection.open('s1-free-3',()=>i/20);assert.equal(item.type,COSMETIC_SLOTS[i%5]);assert.equal(item.palette,Math.floor(i/5));assert.ok(cosmeticVisual(item));assert.ok(p.collection.equip(item.id));}const {p}=fixture();p.pass.claim(3,'free');for(const value of [-1,1,NaN,Infinity])assert.equal(p.collection.open('s1-free-3',()=>value),null);assert.equal(p.collection.open('missing'),null);assert.equal(p.collection.equip('missing'),false);assert.equal(p.collection.equip('s1-free-3'),false);assert.equal(p.collection.unequip('coins'),false);});
test('direct rewards equip independently, replace same slot and mystery opens',()=>{const {p,storage}=fixture();for(let n=1;n<=50;n++)p.pass.claim(n,'premium');const items=p.collection.items();for(const slot of COSMETIC_SLOTS){const owned=items.filter(i=>i.type===slot);for(const item of owned)assert.ok(p.collection.equip(item.id));assert.equal(p.collection.equipped(slot).id,owned.at(-1).id);}const mystery=items.find(i=>i.type==='mystery');assert.ok(p.collection.open(mystery.id,()=>0));const reload=new ProfileStore(storage);for(const slot of COSMETIC_SLOTS)assert.equal(reload.collection.equipped(slot).id,p.collection.equipped(slot).id);});

test('color choices persist per owned object without changing Pass rewards or balances',()=>{const {p,storage}=fixture();for(let n=1;n<=50;n++)p.pass.claim(n,'premium');const balls=p.collection.items().filter(i=>i.type==='ball'),first=balls[0],second=balls[1];const inventory=structuredClone(p.data.passInventory),balances=[p.data.xp,p.data.coins,p.data.tokens,p.data.seasonXp];assert.ok(p.collection.equip(first.id));assert.ok(p.collection.setColor(first.id,2));assert.equal(p.collection.equipped('ball').palette,2);assert.ok(p.collection.setColor(second.id,1));assert.equal(p.collection.equipped('ball').palette,2);const reload=new ProfileStore(storage);assert.equal(reload.collection.equipped('ball').palette,2);assert.equal(reload.collection.appearance(reload.collection.item(second.id)).palette,1);assert.deepEqual(p.data.passInventory,inventory);assert.deepEqual([p.data.xp,p.data.coins,p.data.tokens,p.data.seasonXp],balances);for(const invalid of [-1,4,1.5,NaN,'2'])assert.equal(p.collection.setColor(first.id,invalid),false);assert.equal(p.collection.setColor('missing',0),false);assert.equal(p.collection.setColor('s1-premium-3',0),false);});
