import test from 'node:test';
import assert from 'node:assert/strict';
import { TouchInput,combineTouch } from '../src/touch-input.js';
import { drive,createPlayer } from '../src/player.js';
import { createBall } from '../src/ball.js';
import { BallControl } from '../src/ball-control.js';
import { MobileCamera } from '../src/mobile-camera.js';
import { CONFIG as C } from '../src/config.js';
const base={axis:0,boost:false,jump:false,shoot:false,aimX:0,aimY:0};
const vectors=[['↑',0,-1],['↗',1,-1],['→',1,0],['↘',1,1],['↓',0,1],['↙',-1,1],['←',-1,0],['↖',-1,-1]];
for(const [name,x,y] of vectors){
  test(`mobile V2 ${name} : vecteur tactile normalisé`,()=>{const t=new TouchInput();t.start(1,'move',x,y);const i=combineTouch(base,t.read());assert.ok(i.touchDirection);assert.ok(Math.abs(Math.hypot(i.touchDirection.x,i.touchDirection.y)-1)<1e-9);assert.equal(Math.sign(i.touchDirection.x),Math.sign(x));assert.equal(Math.sign(i.touchDirection.y),Math.sign(y));});
  test(`mobile V2 ${name} : poussée JET orientée et consommation inchangée`,()=>{const p=createPlayer('fluid'),reference=createPlayer('fluid');drive(reference,{},C.step);drive(p,{boost:true,touchDirection:{x,y}},C.step);const n=Math.hypot(x,y);assert.ok(Math.abs(p.vx-reference.vx-C.thrust*C.step*x/n)<1e-8);assert.ok(Math.abs(p.vy-reference.vy-C.thrust*C.step*y/n)<1e-8);assert.equal(p.fuel,100-C.fuelUse*C.step);});
}
test('mobile V2 : aucune propulsion verticale gratuite sans JET, huit directions',()=>{for(const [,x,y]of vectors){const p=createPlayer('fluid'),reference=createPlayer('fluid');for(let i=0;i<60;i++){drive(p,{axis:x,touchDirection:{x,y}},C.step);drive(reference,{axis:x},C.step);}assert.equal(p.vx,reference.vx);assert.equal(p.vy,reference.vy);assert.equal(p.fuel,reference.fuel);}});
test('mobile V2 : au sol, orientation ne crée aucun mouvement vertical',()=>{for(const [,x,y]of vectors){const p=createPlayer('fluid'),reference=createPlayer('fluid');p.grounded=reference.grounded=true;drive(p,{axis:x,touchDirection:{x,y}},C.step);drive(reference,{axis:x},C.step);assert.equal(p.vy,reference.vy);assert.equal(p.vx,reference.vx);}});
test('mobile V2 : décollage au sol garde le JET vertical existant',()=>{const p=createPlayer('fluid'),ref=createPlayer('fluid');p.grounded=ref.grounded=true;drive(p,{boost:true,touchDirection:{x:1,y:0}},C.step);drive(ref,{boost:true},C.step);assert.equal(p.vy,ref.vy);assert.equal(p.vx,ref.vx);});
test('mobile V2 : SAUT + direction conserve impulsion et ne répète pas le saut',()=>{const p=createPlayer('fluid');p.grounded=true;drive(p,{jump:true,touchDirection:{x:1,y:-1}},C.step);assert.equal(p.vy,Math.max(-C.maxRise,-C.jumpSpeed+C.gravity*C.step));const vy=p.vy;drive(p,{jump:true,touchDirection:{x:1,y:-1}},C.step);assert.equal(p.vy,vy+C.gravity*C.step);});
test('mobile V2 : maintien JET, recharge et inertie après relâchement',()=>{const p=createPlayer('fluid'),ref=createPlayer('fluid');for(let i=0;i<120;i++){drive(p,{boost:true,touchDirection:{x:1,y:0}},C.step);drive(ref,{boost:true},C.step);}assert.equal(p.fuel,ref.fuel);const vx=p.vx;drive(p,{},C.step);drive(ref,{},C.step);assert.ok(p.vx>0&&p.vx<vx);assert.equal(p.fuel,ref.fuel);assert.equal(p.boosting,false);});
test('mobile V2 : vecteur invalide et absence tactile gardent la commande JET classique',()=>{for(const d of [undefined,{x:0,y:0},{x:NaN,y:1}]){const p=createPlayer('fluid'),ref=createPlayer('fluid');drive(p,{axis:1,boost:true,touchDirection:d},C.step);drive(ref,{axis:1,boost:true},C.step);assert.deepEqual(p,ref);}});
test('mobile V2 : TIR glissé fournit visée et mémorise direction au relâchement',()=>{const t=new TouchInput();t.start(1,'shoot');assert.equal(t.read().aimActive,false);t.move(1,1,-1);assert.ok(t.read().aimY<0);t.end(1);const release=t.read();assert.ok(release.releaseAim&&release.aimY<0);assert.equal(release.shoot,false);assert.equal(t.read().aimActive,false);});
test('mobile V2 : petit mouvement sur TIR reste dans la deadzone',()=>{const t=new TouchInput();t.start(1,'shoot');t.move(1,.1,.1);assert.equal(t.read().aimActive,false);t.end(1);assert.equal(t.read().releaseAim,null);});
test('mobile V2 : annuler un glissement ne conserve ni visée ni frappe',()=>{const t=new TouchInput();t.start(1,'shoot');t.move(1,1,-1);t.end(1,true);const i=t.read();assert.equal(i.releaseAim,null);assert.ok(i.cancelShot);assert.equal(i.shoot,false);});
test('mobile V2 : direction + JET + glissement TIR indépendants à trois doigts',()=>{const t=new TouchInput();t.start(1,'move',1,-1);t.start(2,'boost');t.start(3,'shoot');t.move(3,-1,-1);let i=combineTouch(base,t.read());assert.ok(i.boost&&i.shoot&&i.touchDirection.x>0&&i.aimX<0);t.end(2);i=combineTouch(base,t.read());assert.ok(!i.boost&&i.shoot&&i.touchDirection.y<0);});
test('mobile V2 : glissement puis relâchement charge exactement 0,7 s et frappe dans la direction finale',()=>{const t=new TouchInput(),c=new BallControl(),p=createPlayer('fluid'),b=createBall();Object.assign(p,{x:300,y:606});Object.assign(b,{x:339,y:625,vx:0,vy:0});t.start(1,'shoot');for(let j=0;j<100;j++)c.update(p,b,t.read(),C.step);assert.equal(c.charge,.7);t.move(1,1,-1);t.end(1);c.update(p,b,t.read(),C.step);assert.ok(b.vx>600&&b.vy<-600);assert.ok(Math.abs(Math.hypot(b.vx,b.vy)-1000)<1e-8);assert.equal(c.indicator,null);});
function scene(){const player=createPlayer('fluid'),bot=createPlayer('heavy'),ball=createBall();Object.assign(player,{x:300,y:606});Object.assign(bot,{x:980,y:606});return {player,bot,ball};}
test('caméra mobile équilibrée : zoom cible 1,30 sans mutation physique',()=>{const m=scene(),before=structuredClone(m),c=new MobileCamera();c.update(m,true);assert.equal(c.zoom,1.3);assert.deepEqual(m,before);for(const p of [m.player,m.bot,m.ball])assert.ok(c.project(p.x,p.y).visible);});
test('caméra desktop : cadrage identité, même après une session mobile',()=>{const m=scene(),c=new MobileCamera();c.update(m,true);c.update(m,false);assert.equal(c.zoom,1);assert.deepEqual(c.project(300,600),{x:300,y:600,visible:true});});
test('caméra mobile : élargit immédiatement pour les acteurs éloignés et les buts',()=>{const m=scene(),c=new MobileCamera();c.update(m,true);m.player.x=101;m.bot.x=1179;m.ball.x=1250;m.ball.y=430;c.update(m,true);assert.ok(c.zoom<1.1);for(const p of [m.player,m.bot,m.ball])assert.ok(c.project(p.x,p.y).visible);assert.ok(c.project(C.goalRight,448).visible);});
test('caméra mobile : garde les trois acteurs visibles sur toute l’arène sans modifier les hitboxes',()=>{const m=scene(),c=new MobileCamera();for(let i=0;i<200;i++){m.player.x=101+(i*67)%1078;m.bot.x=101+(i*131)%1078;m.player.y=138+(i*47)%468;m.bot.y=138+(i*97)%468;m.ball.x=19+(i*59)%1242;m.ball.y=119+(i*73)%506;c.update(m,true);for(const p of [m.player,m.bot,m.ball])assert.ok(c.project(p.x,p.y).visible);}assert.equal(m.ball.r,C.ballRadius*C.ballScale);assert.equal(m.player.w,38);assert.equal(m.player.h,76);});
test('caméra mobile : ballon agrandi de 20 % sans muter les autres tailles',()=>{const b=createBall();assert.equal(b.r,C.ballRadius*C.ballScale);assert.equal(new MobileCamera().zoom,1);});
