import test from 'node:test';
import assert from 'node:assert/strict';
import {ProfileStore} from '../src/profile-store.js';
import {PASS_LEVELS} from '../src/season-pass.js';
function fixture(old={xp:0,completed:[]}){const values=new Map([['jetclash.etape2.profile.v1',JSON.stringify(old)]]);const storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)};return {p:new ProfileStore(storage),reload:()=>new ProfileStore(storage)};}
test('XP, seuil exact, plafond 50 et valeurs invalides',()=>{const {p}=fixture();assert.equal(p.pass.level,0);p.pass.addXp(999);assert.equal(p.pass.level,0);p.pass.addXp(1);assert.equal(p.pass.level,1);for(const n of [-1,NaN,Infinity,1.5])assert.equal(p.pass.addXp(n),false);p.pass.addXp(99000);assert.equal(p.pass.level,50);assert.equal(p.pass.snapshot().progress,1000);});
test('gratuit, Coins, Jetons et anti-double attribution après reload',()=>{const {p,reload}=fixture();assert.equal(p.pass.claim(2,'free'),false);p.pass.addXp(5000);assert.equal(p.pass.claim(2,'free'),true);assert.equal(p.data.coins,100);assert.equal(p.pass.claim(5,'free'),true);assert.equal(p.data.tokens,5);assert.equal(p.pass.claim(2,'free'),false);const q=reload();assert.equal(q.data.coins,100);assert.equal(q.data.tokens,5);assert.equal(q.pass.claim(2,'free'),false);assert.equal(q.pass.level,5);});
test('Premium requis, activation et récompense unique',()=>{const {p,reload}=fixture();p.pass.addXp(2000);assert.equal(p.pass.claim(2,'premium'),false);p.pass.setPremium(true);assert.equal(p.pass.claim(2,'premium'),true);assert.equal(p.data.coins,200);assert.equal(reload().pass.claim(2,'premium'),false);assert.equal(reload().pass.snapshot().premium,true);});
test('migration douce conserve monnaies, cosmétiques, paramètres et XP saison',()=>{const old={xp:1500,completed:['match'],seasonXp:2300,coins:88,tokens:3,skins:['fluid'],settings:{sound:false},custom:{a:1}};const {p,reload}=fixture(old);for(const [k,v] of Object.entries(old))assert.deepEqual(p.data[k],v);assert.equal(reload().pass.level,2);});
test('défis branchés sur la progression centrale',()=>{const {p}=fixture();p.pass.addXp(925);p.challenges.record('training');assert.equal(p.data.seasonXp,1000);assert.equal(p.data.pass.level,1);p.challenges.record('training');assert.equal(p.data.seasonXp,1000);});
test('niveau 50 exclusif déverrouillé, inventaire et caisses persistants',()=>{const {p,reload}=fixture();p.pass.addXp(49000);assert.equal(p.pass.claim(50,'free'),false);p.pass.addXp(1000);assert.equal(p.pass.claim(50,'free'),true);assert.equal(p.pass.claim(3,'free'),true);assert.equal(p.data.passInventory.length,2);assert.equal(reload().data.passInventory.length,2);assert.equal(reload().pass.claim(50,'free'),false);});
test('distribution sur 50 niveaux : 11 caisses, 5 Coins et 5 Jetons par piste',()=>{assert.equal(PASS_LEVELS.length,50);for(const track of ['free','premium'])for(const [type,count] of [['crate',11],['coins',5],['tokens',5]])assert.equal(PASS_LEVELS.filter(row=>row[track].type===type).length,count);});
test('stockage indisponible : attribution unique dans la session et avertissement',()=>{const p=new ProfileStore({getItem(){throw Error();},setItem(){throw Error();}});p.pass.addXp(2000);assert.equal(p.pass.claim(2,'free'),true);assert.equal(p.pass.claim(2,'free'),false);assert.ok(p.warning);});
test('solde invalide et requêtes invalides ne consomment pas la récompense',()=>{const {p}=fixture();p.pass.addXp(2000);p.data.coins='invalid';assert.equal(p.pass.claim(2,'free'),false);assert.equal(p.pass.claim(2,'other'),false);assert.equal(p.pass.claim(51,'free'),false);assert.equal(p.data.pass.claimed.length,0);});
