import { STATES } from './match.js';
export class HUD{
  constructor(){this.lastState=null;this.announcementText='';this.ids={};for(const id of ['menu','hud','fuel-hud','score-player','score-bot','timer','mode-label','fuel-player','fuel-bot','announcement','result','result-title','result-score','xp-earned','xp-breakdown','result-level','profile','save-warning','game-shell'])this.ids[id]=document.getElementById(id);}
  update(m){const el=this.ids,menu=m.state===STATES.MENU,result=m.state===STATES.POST_MATCH;el.menu.hidden=!menu;el.result.hidden=!result;el.hud.hidden=menu||result;el['fuel-hud'].hidden=menu||result;el['score-player'].textContent=m.score.player;el['score-bot'].textContent=m.score.bot;
    const seconds=Math.ceil(m.remaining);el.timer.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;el['mode-label'].textContent=m.overtime?'MORT SUBITE':'MATCH';el['game-shell'].classList.toggle('overtime',!!m.overtime);el['fuel-player'].value=m.player.fuel;el['fuel-bot'].value=m.bot.fuel;
    let announcement='';if(m.state===STATES.PRE_ROUND)announcement=`${Math.max(1,Math.ceil(m.phase))}<small>PRÉPARE-TOI</small>`;else if(m.state===STATES.GOAL_SCORED)announcement=m.lastGoal==='player'?'BUT POUR FLUID !':'BUT POUR HEAVY !';if(announcement!==this.announcementText){el.announcement.innerHTML=announcement;this.announcementText=announcement;}el.announcement.hidden=!announcement;
    el.profile.textContent=`Niveau ${m.profile.level} · ${m.profile.data.xp} XP`;el['save-warning'].hidden=!m.profile.warning;el['save-warning'].textContent=m.profile.warning;
    if(result&&this.lastState!==m.state){el['result-title'].textContent=m.result==='win'?'VICTOIRE !':'DÉFAITE';el['result-score'].textContent=`${m.score.player} — ${m.score.bot}`;el['xp-earned'].textContent=`+${m.reward} XP`;el['xp-breakdown'].textContent=`Match terminé : 100 · Victoire : ${m.result==='win'?50:0} · Buts : ${m.score.player*10}`;el['result-level'].textContent=`Niveau ${m.profile.level} · ${m.profile.data.xp%1000} / 1 000 XP vers le niveau suivant`;document.getElementById('replay').focus();}
    if(menu&&this.lastState!==m.state&&this.lastState!==null)document.getElementById('start').focus();this.lastState=m.state;
  }
}
